### ISSUE TITLE
Autoupdate branch broken

### ISSUE THREAD

**Issue by JigSawFr** [wernight/docker-plex-media-server#13]
Hi,
I'm Unable to start autoupdate tag, as mentionned in an old issue https://github.com/wernight/docker-plex-media-server/issues/12:

```
+ /retrieve_plex_download_url.py
Retrieving the latest Plex release for PlexPass users...
Traceback (most recent call last):
  File "/retrieve_plex_download_url.py", line 52, in <module>
    print(retrieve_latest_download_url(login, password))
  File "/retrieve_plex_download_url.py", line 41, in retrieve_latest_download_url
    assert len(links) == 1
AssertionError
+ curl -L -o plexmediaserver.deb
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
8192
+ /retrieve_plex_download_url.py
Retrieving the latest Plex release for PlexPass users...
Traceback (most recent call last):
  File "/retrieve_plex_download_url.py", line 52, in <module>
    print(retrieve_latest_download_url(login, password))
  File "/retrieve_plex_download_url.py", line 41, in retrieve_latest_download_url
    assert len(links) == 1
AssertionError
+ curl -L -o plexmediaserver.deb
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

Image is up to date

```
[10:48:49] # docker pull wernight/plex-media-server:autoupdate
autoupdate: Pulling from wernight/plex-media-server
Digest: sha256:e16a25436274c6414979eae0afc442e6e8fa00d8881ca31fd775eb1d9eb99902
Status: Image is up to date for wernight/plex-media-server:autoupdate
```

Latest is working but not autoupdate.
Thanks you

**Comment by wernight** [comment]
Crap they now have two links matching... Ok Plex thanks for the com.

**Comment by wernight** [comment]
Strangely it's working on my side. Could be a locale issue. I'm now forcing the locale.

**Comment by JigSawFr** [comment]
Working as well, no locale issue, the password was wrong.
Maybe need to handle wrong password or error message from Plex.tv ?
Thanksyou and sorry for disturbing you.

**Comment by wernight** [comment]
Yes that's probably a good improvement I agree it should be a clear message when possible.
