### ISSUE TITLE
Restarting autoupdate fail

### ISSUE THREAD

**Issue by JigSawFr** [wernight/docker-plex-media-server#6]
Hi,
I'm using autoupdate branch from your nice docker image for Plex,
But to update Plex, i need to stop container, remove it and run command to create it.
If i want to just restart it, it will fail on retrieving latest Plex version:

```
+ /retrieve_plex_download_url.py
Retrieving the latest Plex release for PlexPass users...
Traceback (most recent call last):
  File "/retrieve_plex_download_url.py", line 44, in <module>
    print(retrieve_latest_download_url(login, password))
  File "/retrieve_plex_download_url.py", line 21, in retrieve_latest_download_url
    browser.open('https://plex.tv/users/sign_in')
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 403: request disallowed by robots.txt
+ curl -L -o plexmediaserver.deb
curl: /usr/lib/plexmediaserver/libcurl.so.4: no version information available (required by curl)
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

But working by running original command to create plex container :)

**Comment by wernight** [comment]
If you do a `docker pull wernight/plex-media-server:autoupdate` it should now be fixed already via a workaround. The real proper fix is causing me some trouble, see https://github.com/wernight/docker-plex-media-server/issues/3#issue-114479179

**Comment by JigSawFr** [comment]
Yes, solved, it's now working as well :)
Thanks you
